version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: wikijs_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: wikijs
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: wikijs_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - wikinet

  wikijs:
    image: requarks/wiki:latest
    container_name: wikijs
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      - DB_TYPE=postgres
      - DB_HOST=wikijs_postgres
      - DB_USER=wikijs
      - DB_PASS=wikijs_pass
      - DB_NAME=wikijs
      - DB_SSL=false
      - DB_PORT=5432
    ports:
      - "3002:3000"
    # volumes:
    #   - ./config.yml:/wiki/config.yml:ro
    networks:
      - wikinet

volumes:
  pgdata:

networks:
  wikinet:
