version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: wikijs_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: wikijs
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: wikijs_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - wikinet

  wikijs:
    image: requarks/wiki:2
    container_name: wikijs
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "3002:3000"
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijs_pass
      DB_NAME: wikijs
      DB_SSL: "false"         # Set as string to avoid issues
    networks:
      - wikinet

volumes:
  pgdata:

networks:
  wikinet:
